import {
  formatMoney,
  formatMoneyShort,
  formatNumber,
  formatNumberShort,
  formatHours,
  formatDuration,
} from './format';

/**
 * Every selectable metric in one place. Adding a metric here makes it available
 * to the chart, the stat cards, the channel table and the daily log at once.
 */
export const METRICS = {
  revenue: {
    id: 'revenue',
    label: 'Revenue',
    shortLabel: 'Revenue',
    dayKey: 'effectiveRevenue',
    summaryKey: 'effectiveRevenue',
    deltaKey: 'effectiveRevenue',
    channelKey: 'revenue',
    monthKey: 'revenue',
    format: (v) => formatMoney(v),
    formatShort: formatMoneyShort,
    color: '#22c55e',
    estimable: true,
    description: 'Estimated revenue reported by YouTube, in SEK',
  },
  views: {
    id: 'views',
    label: 'Total views',
    shortLabel: 'Views',
    dayKey: 'views',
    summaryKey: 'views',
    deltaKey: 'views',
    channelKey: 'views',
    monthKey: 'views',
    format: formatNumber,
    formatShort: formatNumberShort,
    color: '#3b82f6',
  },
  lfViews: {
    id: 'lfViews',
    label: 'Long-form views',
    shortLabel: 'Long-form',
    dayKey: 'lf_views',
    summaryKey: 'lf_views',
    deltaKey: 'lf_views',
    channelKey: 'lfViews',
    monthKey: 'lfViews',
    format: formatNumber,
    formatShort: formatNumberShort,
    color: '#f59e0b',
    description: 'Views on regular videos (videoOnDemand). Updated in near real time.',
  },
  sfViews: {
    id: 'sfViews',
    label: 'Shorts views',
    shortLabel: 'Shorts',
    dayKey: 'sf_views',
    summaryKey: 'sf_views',
    deltaKey: 'sf_views',
    channelKey: 'sfViews',
    monthKey: 'sfViews',
    format: formatNumber,
    formatShort: formatNumberShort,
    color: '#a855f7',
  },
  watchHours: {
    id: 'watchHours',
    label: 'Watch time',
    shortLabel: 'Watch time',
    dayKey: 'watch_hours',
    summaryKey: 'watch_hours',
    deltaKey: 'watch_hours',
    channelKey: 'watchHours',
    monthKey: 'watchHours',
    format: formatHours,
    formatShort: formatNumberShort,
    color: '#06b6d4',
  },
  subsNet: {
    id: 'subsNet',
    label: 'Net subscribers',
    shortLabel: 'Subs',
    dayKey: 'subs_net',
    summaryKey: 'subs_net',
    deltaKey: 'subs_net',
    channelKey: 'subsNet',
    monthKey: 'subsNet',
    format: (v) => (v > 0 ? `+${formatNumber(v)}` : formatNumber(v)),
    formatShort: formatNumberShort,
    color: '#ec4899',
  },
  rpm: {
    id: 'rpm',
    label: 'RPM',
    shortLabel: 'RPM',
    dayKey: 'rpm',
    summaryKey: 'rpm',
    deltaKey: 'rpm',
    channelKey: 'rpm',
    monthKey: 'rpm',
    format: (v) => formatMoney(v),
    formatShort: formatMoneyShort,
    color: '#facc15',
    aggregate: 'rate',
    description: 'Revenue per 1000 total views',
  },
  cpm: {
    id: 'cpm',
    label: 'CPM',
    shortLabel: 'CPM',
    dayKey: 'cpm',
    summaryKey: 'cpm',
    deltaKey: 'cpm',
    channelKey: 'cpm',
    monthKey: 'cpm',
    format: (v) => formatMoney(v),
    formatShort: formatMoneyShort,
    color: '#fb923c',
    aggregate: 'rate',
    description: 'Gross revenue per 1000 monetised playbacks',
  },
  avgViewDuration: {
    id: 'avgViewDuration',
    label: 'Avg view duration',
    shortLabel: 'Avg duration',
    dayKey: 'avg_view_duration',
    summaryKey: 'avg_view_duration',
    deltaKey: 'avg_view_duration',
    channelKey: 'avgViewDuration',
    monthKey: 'avgViewDuration',
    format: formatDuration,
    formatShort: (v) => formatDuration(v),
    color: '#94a3b8',
    aggregate: 'rate',
  },
};

export const METRIC_ORDER = [
  'revenue',
  'views',
  'lfViews',
  'sfViews',
  'watchHours',
  'subsNet',
  'rpm',
  'cpm',
];

/** Headline cards shown above the chart. */
export const HEADLINE_METRICS = ['revenue', 'views', 'lfViews', 'rpm'];

/** Per-channel line colours, reused across every chart for consistency. */
export const CHANNEL_COLORS = [
  '#3b82f6',
  '#22c55e',
  '#f59e0b',
  '#a855f7',
  '#ef4444',
  '#06b6d4',
  '#ec4899',
  '#84cc16',
  '#fb923c',
  '#8b5cf6',
];

export function channelColor(index) {
  return CHANNEL_COLORS[index % CHANNEL_COLORS.length];
}
